// Copyright (c) Josef Pihrt. All rights reserved. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// <auto-generated>

using System;

namespace Roslynator.CodeAnalysis.CSharp
{
    public static partial class DiagnosticIdentifiers
    {
        public const string UsePropertySyntaxNodeSpanStart = "ROS0001";
        public const string UsePropertySyntaxNodeRawKind = "ROS0002";
        public const string UnnecessaryConditionalAccess = "ROS0003";
        public const string UsePatternMatching = "ROS0004";
        public const string CallAnyInsteadOfAccessingCount = "ROS0005";
        public const string UnnecessaryNullCheck = "ROS0006";
        public const string UseElementAccess = "ROS0007";
        public const string UseReturnValue = "ROS0008";
        public const string CallLastInsteadOfUsingElementAccess = "ROS0009";
        public const string UnknownLanguageName = "ROS0010";
        public const string SpecifyExportCodeRefactoringProviderAttributeName = "ROS0011";
        public const string SpecifyExportCodeFixProviderAttributeName = "ROS0012";
    }
}